#!/bin/sh /etc/rc.common
# /etc/init.d/http-service
# Enable: /etc/init.d/http-service enable

USE_PROCD=1
START=95
STOP=01


start_service() {
	procd_open_instance
	procd_set_param command \
		/usr/sbin/shell2http -no-index -add-exit -timeout=1 -port=20000 \
			/status "/root/status.sh" \
			/4/status "/root/server4.sh status" \
			/4/start "/root/server4.sh start"
	procd_close_instance
}
