#!/bin/sh /etc/rc.common
# /etc/init.d/http-service
# Enable: /etc/init.d/http-service enable

USE_PROCD=1
START=95
STOP=01


start_service() {
	procd_open_instance
	procd_set_param command \
		/usr/sbin/shell2http -no-index -add-exit -one-thread -cache=5 -timeout=5 -port=20000 \
			/status "/root/status.sh" \
			/pdx-001/status "/root/pdx-001.sh status" \
			/pdx-001/start "/root/pdx-001.sh start" \
			/pdx-002/status "/root/pdx-002.sh status" \
			/pdx-002/start "/root/pdx-002.sh start" \
			/pdx-003/status "/root/pdx-003.sh status" \
			/pdx-003/start "/root/pdx-003.sh start" \
			/pdx-004/status "/root/pdx-004.sh status" \
			/pdx-004/start "/root/pdx-004.sh start"
	procd_close_instance
}
