#!/bin/sh /etc/rc.common
# /etc/init.d/http-service
# Enable: /etc/init.d/http-service enable

USE_PROCD=1
START=95
STOP=01


start_service() {
	procd_open_instance
	procd_set_param command \
		/usr/sbin/shell2http -no-index -add-exit -one-thread -cache=5 -timeout=30 -port=20000 \
			/ping "echo 'PONG'" \
			/status "/root/status.sh"
	procd_close_instance
}
