#!/bin/sh /etc/rc.common
# /etc/init.d/server-status
# Enable: /etc/init.d/server-status enable

USE_PROCD=1
START=95
STOP=01


start_service() {
	procd_open_instance
	procd_set_param command \
		/root/status.sh
	procd_close_instance
}
